# Generated by Django 4.2.24 on 2025-09-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Phone_Number', models.IntegerField()),
                ('Feedback', models.CharField(max_length=50)),
                ('Date', models.DateField()),
            ],
        ),
    ]
