# Generated by Django 4.2.24 on 2025-09-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartooncrazeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Phone_Number',
            field=models.CharField(max_length=10),
        ),
    ]
