# Generated by Django 4.2.24 on 2025-09-27 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartooncrazeapp', '0002_alter_feedback_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Feedback',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Phone_Number',
            new_name='phone_number',
        ),
    ]
