# Generated by Django 4.2.24 on 2025-10-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartooncrazeapp', '0005_remove_feedback_name_remove_feedback_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
