# Generated by Django 4.2.24 on 2025-10-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartooncrazeapp', '0006_remove_feedback_user_feedback_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
